const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const partSchema = new Schema
({
    "us1": "String",
    "or1": "String",
    "or2": "String",
    "or3": "String",
    "or4": "String",
    "or5": "String",
    "or7": "String",
    "cu1": "String",
    "cu2": "String",
    "cu3": "String",
    "pa1": "String",
    "pa2": "String",
    "pa3": "String",
    "pa4": "String",
    "pa5": "String",
    "pa6": "String",
    "pa7": "String",
    "pa8": "String",
    "pa9": "String",
    "pa10": "String",
    "pa11": "String",
    "pa12": "String",
    "pa13": "String",
"pa14": "String",
"pa15": "String",
"pa16": "String",
"pa17": "String",
"pa18": "String",
"pa19": "String",
"pa20": "String",
"pa21": "String",
"pa22": "String",
"pa23": "String",
"pa24": "String",
"pa25": "String",
"pa26": "String",
"pa27": "String",
"pa28": "String",
"pa29": "String",
"pa30": "String",
"pa31": "String",
"pa32": "String",
"pa33": "String",
"pa34": "String",
"pa35": "String",
"pa36": "String",
"pa37": "String",
"pa38": "String",
"pa39": "String",
"pa40": "String",
"pa41": "String",
"pa42": "String",
"pa43": "String",
"pa44": "String",
"pa45": "String",
"pa46": "String",
"pa47": "String",
"pa48": "String",
"pa49": "String",
"pa50": "String",
"pa51": "String",
"pa52": "String",
"pa53": "String",
"pa54": "String",
"pa55": "String",
"pa56": "String",
"pa57": "String",
"pa58": "String",
"pa59": "String"

  }
  );

module.exports = mongoose.model("part", partSchema);